# Generated by Django 2.1.5 on 2019-02-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('questions', models.ManyToManyField(related_query_name='test', to='testingapp.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestRunAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingapp.Question')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingapp.TestRun')),
            ],
        ),
        migrations.AddField(
            model_name='testrun',
            name='questions',
            field=models.ManyToManyField(through='testingapp.TestRunAnswers', to='testingapp.Question'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingapp.Test'),
        ),
    ]
