# Generated by Django 2.1.5 on 2019-02-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='testingapp.Question'),
        ),
    ]
