# Generated by Django 2.1.5 on 2019-02-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0002_auto_20190218_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrunanswers',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
