# Generated by Django 2.1.5 on 2019-02-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0005_note_noteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteitem',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='note_item', to='testingapp.Note'),
        ),
    ]
