# Generated by Django 2.1.5 on 2019-02-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0007_auto_20190222_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrun',
            options={'verbose_name': 'test_run'},
        ),
    ]
