# Generated by Django 2.1.5 on 2019-02-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0008_auto_20190222_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrun',
            options={'verbose_name': 'testrun'},
        ),
    ]
