# Generated by Django 2.1.5 on 2019-02-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0009_auto_20190222_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrunanswers',
            name='answer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
