# Generated by Django 2.1.5 on 2019-02-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0010_auto_20190225_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrunanswers',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
