# Generated by Django 2.1.5 on 2019-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0011_auto_20190225_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrunanswers',
            name='answer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
