# Generated by Django 2.1.5 on 2019-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0012_auto_20190226_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrunanswers',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
